#!/bin/bash
cd ../../
make
echo "Test case: running login1..."
./output current_User_Accounts_File.uaf available_Items_File.ai daily_Transaction_file.tra < "Test_Cases/login/login1.in" > "Test_Cases/login/results/login1.txt"
echo "DONE"
echo "Test case: running login2..."
./output current_User_Accounts_File.uaf available_Items_File.ai daily_Transaction_file.tra < "Test_Cases/login/login2.in" > "Test_Cases/login/results/login2.txt"
echo "DONE"
echo "Test case: running login3..."
./output current_User_Accounts_File.uaf available_Items_File.ai daily_Transaction_file.tra < "Test_Cases/login/login3.in" > "Test_Cases/login/results/login3.txt"
echo "DONE"
echo "Test case: running login4..."
./output current_User_Accounts_File.uaf available_Items_File.ai daily_Transaction_file.tra < "Test_Cases/login/login4.in" > "Test_Cases/login/results/login4.txt"
echo "DONE"
echo "Test case: running login5..."
./output current_User_Accounts_File.uaf available_Items_File.ai daily_Transaction_file.tra < "Test_Cases/login/login5.in" > "Test_Cases/login/results/login5.txt"
echo "DONE"
echo "Test case: running login6..."
./output current_User_Accounts_File.uaf available_Items_File.ai daily_Transaction_file.tra < "Test_Cases/login/login6.in" > "Test_Cases/login/results/login6.txt"
echo "DONE"
echo "Test case: running login7..."
./output current_User_Accounts_File.uaf available_Items_File.ai daily_Transaction_file.tra < "Test_Cases/login/login7.in" > "Test_Cases/login/results/login7.txt"
echo "DONE"
